import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import 'gpa_model.dart';

/// Builds a printable GPA report from the working semesters, matching the
/// layout of the Study Zone web calculator (dashboard summary + per-semester tables).
class GpaPdf {
  static Future<pw.Document> build(List<GpaSemester> semesters) async {
    // Arabic/Urdu-capable fonts (subject names are RTL). Downloaded & cached by
    // the printing package; falls back to default if unavailable.
    pw.Font base;
    pw.Font bold;
    try {
      base = await PdfGoogleFonts.notoNaskhArabicRegular();
      bold = await PdfGoogleFonts.notoNaskhArabicBold();
    } catch (_) {
      base = await PdfGoogleFonts.nunitoRegular();
      bold = await PdfGoogleFonts.nunitoBold();
    }

    final logoBytes = await rootBundle.load('assets/images/studyzonelogo-square.png');
    final logo = pw.MemoryImage(logoBytes.buffer.asUint8List());

    final doc = pw.Document();

    var globalCredits = 0.0;
    var globalPoints = 0.0;
    for (final s in semesters) {
      globalCredits += s.totalCredits;
      globalPoints += s.totalPoints;
    }
    final overallCgpa = globalCredits > 0 ? globalPoints / globalCredits : 0.0;

    const primary = PdfColor.fromInt(0xFF4F46E5);
    const muted = PdfColor.fromInt(0xFF6B7280);

    doc.addPage(
      pw.MultiPage(
        theme: pw.ThemeData.withFont(base: base, bold: bold),
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(24),
        header: (context) => pw.Container(
          margin: const pw.EdgeInsets.only(bottom: 12),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            crossAxisAlignment: pw.CrossAxisAlignment.center,
            children: [
              pw.Text('GPA / CGPA Report',
                  style: pw.TextStyle(fontSize: 18, color: primary, fontWeight: pw.FontWeight.bold)),
              pw.Image(logo, height: 42),
            ],
          ),
        ),
        build: (context) => [
          // Dashboard summary
          pw.Container(
            padding: const pw.EdgeInsets.all(16),
            decoration: pw.BoxDecoration(
              color: primary,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(10)),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
              children: [
                _stat('Overall CGPA', overallCgpa.toStringAsFixed(2)),
                _stat('Total Credits', _trim(globalCredits)),
                _stat('Total Points', globalPoints.toStringAsFixed(2)),
              ],
            ),
          ),
          pw.SizedBox(height: 16),
          for (final sem in semesters) ...[
            _semesterBlock(sem, primary, muted),
            pw.SizedBox(height: 16),
          ],
          pw.SizedBox(height: 8),
          pw.Text('Generated by Study Zone App',
              style: pw.TextStyle(fontSize: 9, color: muted)),
        ],
      ),
    );
    return doc;
  }

  static pw.Widget _stat(String label, String value) {
    return pw.Column(
      children: [
        pw.Text(label, style: const pw.TextStyle(color: PdfColors.white, fontSize: 10)),
        pw.SizedBox(height: 4),
        pw.Text(value,
            style: pw.TextStyle(color: PdfColors.white, fontSize: 22, fontWeight: pw.FontWeight.bold)),
      ],
    );
  }

  static pw.Widget _semesterBlock(GpaSemester sem, PdfColor primary, PdfColor muted) {
    final headers = ['Subject', 'Fac', 'Fin', 'Total', 'Cr', 'Grade', 'GPA', 'Pts'];
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.stretch,
      children: [
        pw.Text(sem.title.text,
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 6),
        pw.TableHelper.fromTextArray(
          headerStyle: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: PdfColors.white),
          headerDecoration: pw.BoxDecoration(color: primary),
          cellStyle: const pw.TextStyle(fontSize: 9),
          cellAlignment: pw.Alignment.center,
          cellAlignments: {0: pw.Alignment.centerRight},
          columnWidths: {
            0: const pw.FlexColumnWidth(3),
            1: const pw.FlexColumnWidth(1),
            2: const pw.FlexColumnWidth(1),
            3: const pw.FlexColumnWidth(1.2),
            4: const pw.FlexColumnWidth(1),
            5: const pw.FlexColumnWidth(1.2),
            6: const pw.FlexColumnWidth(1),
            7: const pw.FlexColumnWidth(1),
          },
          headers: headers,
          data: [
            for (final s in sem.subjects)
              [
                s.name.text.trim().isEmpty ? '-' : s.name.text.trim(),
                s.faculty.text.trim().isEmpty ? '-' : s.faculty.text.trim(),
                s.finalMarks.text.trim().isEmpty ? '-' : s.finalMarks.text.trim(),
                s.totalMarks == null ? '-' : _trim(s.totalMarks!),
                s.credits.text.trim(),
                s.grade?.letter ?? '-',
                s.grade == null ? '-' : s.grade!.gpa.toStringAsFixed(2),
                s.counts ? s.points.toStringAsFixed(2) : '0.00',
              ],
          ],
        ),
        pw.SizedBox(height: 6),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.end,
          children: [
            pw.Text('Credits: ${_trim(sem.totalCredits)}    ',
                style: pw.TextStyle(fontSize: 10, color: muted)),
            pw.Text('Points: ${sem.totalPoints.toStringAsFixed(2)}    ',
                style: pw.TextStyle(fontSize: 10, color: muted)),
            pw.Text('Quarterly GPA: ${sem.gpa.toStringAsFixed(2)}',
                style: pw.TextStyle(fontSize: 11, color: primary, fontWeight: pw.FontWeight.bold)),
          ],
        ),
      ],
    );
  }

  static String _trim(double value) {
    if (value == value.roundToDouble()) return value.toInt().toString();
    return value.toString();
  }

  /// Opens the system share sheet with the report.
  static Future<void> share(List<GpaSemester> semesters) async {
    final doc = await build(semesters);
    await Printing.sharePdf(bytes: await doc.save(), filename: 'StudyZone_GPA_Report.pdf');
  }

  /// Opens the print/preview dialog.
  static Future<void> printReport(List<GpaSemester> semesters) async {
    final doc = await build(semesters);
    await Printing.layoutPdf(onLayout: (format) async => doc.save());
  }
}
